### ISSUE TITLE
Multiple tests with same suite and description is not reported

### ISSUE THREAD

**Issue by andreandersson** [sth/karma-summary-reporter#30]
```
describe('truthy-tests', () => {
  it('should be truthy', () => { expect(true).toBeTruthy(); });
  it('should be truthy', () => { expect(1).toBeTruthy(); });
});
```

Will output that `  1 test cases successful in all browsers`, despite it being two successful tests. It seems like only the first test is being reported, and if you have more they are disregarded.

The problem can be found here: https://github.com/sth/karma-summary-reporter/blob/master/index.js#L45

**Comment by sth** [comment]
Fixed in #31 and published in v4.0.1.

Thanks for reporting this!
