### ISSUE TITLE
Print error details

### ISSUE THREAD

**Issue by julkue** [sth/karma-summary-reporter#4]
If something goes wrong you can only see the `x` that indicates a failed test. However, in other reporters a useful detail is printed, e.g. `Expected false to be true` if you have the following code ([Jasmine](https://jasmine.github.io/)):

```javascript
it("should xxxxx", function () {
    expect(false).toBe(true);
});
```

 If you have multiple `expect` statements e.g. inside a `it(...)` block then this gives the necessary information which of them failed.

I would like to see this in this reporter too.

**Comment by sth** [comment]
It is of course useful to have more details about errors, like assertion mismatches or stack traces, but the main intention of this reporter is to display a clear and easy to read summary. I don't think it's the right place to show all the error details.

But you can have two reporters active without problems, one to show all the error details as the tests run and this one to provide a summary in the end. That way you can combine your favorite error reporting with this summary table, like for example:

    reporters: ['spec', 'summary']

I added a section to the Readme file explaining this.

**Comment by julkue** [comment]
That doesn't solve my problem. When running many cross-browser unit tests e.g. on SauceLabs the spec reporter will create thousands of lines. That's why I like to use the summary reporter. But I still like to see error details (only if there are errors)

**Comment by sth** [comment]
I think `spec` can be [configured][1] to reduce it's irrelevant output, with options like `suppressPassed: true`. I haven't tried it recently, but shouldn't this make it's output fairly short in absence of errors?

I personally use karma-mocha-reporter with `output: 'minimal'` configuration to see error details, which works alright for my usage.

 [1]: https://github.com/mlex/karma-spec-reporter#configuration
