### ISSUE TITLE
Unknown character output in Windows OS for ✓ and ✗.

### ISSUE THREAD

**Issue by iH8** [sth/karma-summary-reporter#6]
I've left a pull request with a fix: https://github.com/sth/karma-summary-reporter/pull/5

**Comment by sth** [comment]
Fixed by #5 in v1.4.0.

**Comment by sjones6** [comment]
Recognize I'm commenting on an closed issue here but I'm seeing some trouble with character encoding ... 

I'm getting some strange characters on my windows build server where `process.platform === 'win32'`. This is what is logged out as the cross: `├ù`.

Is this related to the original trouble in this issue or should I open a new one?

**Comment by sth** [comment]
The `├ù` seems to be the "windows compatible" cross character encoded as UTF-8 and then the single bytes interpreted as [code page 437][cp437] or similar. I'm not sure how that happens, when I set a cmd window to such a code page (with `chcp`) I still get the correct output (Windows 7).

I'm also not an expert in Nodejs/Windows Unicode handling, so I don't know what might be going wrong. Do other programs that use Unicode characters show garbled output as well? Does the server use some unusual codepage settings? Does changing the codepage change the behavior?

  [cp437]: https://en.wikipedia.org/wiki/Code_page_437
