### ISSUE TITLE
Upgrade karma dependency to Karma 2.0

### ISSUE THREAD

**Issue by begin-again** [sth/karma-summary-reporter#7]
When I upgraded my project's karma from 1.7.1 to 2.0.0, yarn reported the below warning. Any plans to upgrade this project's karma?

```
karma-summary-reporter@1.4.0" has incorrect peer dependency "karma@^1.2.0"
```

**Comment by sth** [comment]
It seems to work find with the new karma version, without me having to change anything. So karma 2.x is now allowed in the package.json in karma-summary-reporter 1.5.0. If you upgrade karma-summary-reporter the warning should go away.

For anybody else who doesn't want to upgrade to Karma 2.0 yet: No problem, karma-summary-reporter 1.5.0 is still compatible with Karma 1.x as well and there are no plans to change that.
