### ISSUE TITLE
Upgrade Karma dependency to 3.x

### ISSUE THREAD

**Issue by begin-again** [sth/karma-summary-reporter#8]
When I upgraded my project's karma from 2.x, yarn reported the below warning. The reporter seems to run fine with Karma 3 but there is a `deprecated method` warning.

```
karma-summary-reporter@1.5.0" has incorrect peer dependency "karma@^1.2.0 || 2.x"
```

**Comment by sth** [comment]
I don't see a reason why it shouldn't work with karma 3.x, so I added 3,x to the peer dependency. (Published as 1.5.1)
